# name: Deploy Flask App to Azure Web App

# on:
#   push:
#     branches:
#       - main # or any branch you want to deploy

# jobs:
#   build_and_deploy:
#     runs-on: ubuntu-latest
#     steps:
#       - name: Check out the repository
#         uses: actions/checkout@v3

#       - name: Set up Python
#         uses: actions/setup-python@v4
#         with:
#           python-version: "3.11" # Set the Python version for your app

#       - name: Install dependencies
#         run: |
#           python -m pip install --upgrade pip
#           pip install -r requirements.txt
name: Deploy React App to Azure Web App via Docker

on:
  push:
    branches: main

jobs:
  build_and_deploy:
    name: Build, Push Docker Image to Docker Hub and Deploy to Azure
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repo
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Build Docker Image
        run: |
          IMAGE_TAG=${{ github.sha }}  # or $(date +%s) for timestamp
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/multitenant-be:${IMAGE_TAG} .
          echo "IMAGE_TAG=${IMAGE_TAG}" >> $GITHUB_ENV

      - name: Push Docker Image to Docker Hub
        run: |
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/multitenant-be:${{ env.IMAGE_TAG }}

      - name: Log in to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      # - name: Create Staging Slot
      #   run: |
      #     az webapp deployment slot create --name ReactAppDemoUsingDocker --resource-group bluegreendeployment --slot staging
      #   continue-on-error: true # Allow this step to succeed even if the slot already exists

      # Configure Web App for Docker and deploy to staging slot
      - name: "Deploy Docker Image to Azure Web App Slot"
        run: |
          az webapp config container set --name 'ReactAppDemoUsingDocker' \
            --resource-group 'bluegreendeployment' \
            --slot 'staging' \
            --container-image-name ${{ secrets.DOCKERHUB_USERNAME }}/react-img:${{ env.IMAGE_TAG }} \
            --container-registry-url https://index.docker.io/v1/ \
            --container-registry-user ${{ secrets.DOCKERHUB_USERNAME }} \
            --container-registry-password ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v2
        with:
          app-name: "backend-multitenant" # Replace with your Azure Web App name
          slot-name: "production"
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
